name: Notify `Full Stack Open 2020 Progress` channel of any pushes you made to master
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Notify Telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Send a push message with Github info to channel
        uses: appleboy/telegram-action@master
        env:
          CURRENT_COURSE_YEAR: 2020
        with:
          to: ${{ secrets.-1001232219969 }}
          token: ${{ secrets.1241697819:AAGHeBCNT9jDEWvvbmLG6vlL4LjzlGVLdF8 }}
          format: markdown
          args: "${{ secrets.@yiffzer }} pushed one or more commits to `${{ github.repository }}` for Full Stack Open ${{ env.CURRENT_COURSE_YEAR }}\n\n[Link to Github Repository](https://github.com/${{github.repository}}/)"
